name: routerino
description: Add names to routes without a declarative pattern and without build_runner
version: 0.8.0
repository: https://github.com/Tienisto/routerino

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
